### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by gagan144** [NioushaR/LSTM-TensorFlow-for-Timeseries-forecasting#1]
Hi,
Where can we find the dataset?
Regards

**Comment by Ehsan222** [comment]
Hi,
Where can we find the dataset?

**Comment by rabbit200** [comment]
Is the file 'Data.csv' a secret?

**Comment by NioushaR** [comment]
@rabbit200  @Ehsan222  @gagan144 
Thank you for your interest. I am afraid the dataset cannot be shared with the public.

**Comment by rabbit200** [comment]
Thanks so much for your reply, I deeply understand this.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NioushaR/LSTM-TensorFlow-for-Timeseries-forecasting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 凌晨2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NioushaR/LSTM-TensorFlow-for-Timeseries-forecasting] Dataset (#1)





 
@rabbit200  @Ehsan222  @gagan144
 Thank you for your interest. I am afraid the dataset cannot be shared with the public.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
